// Code generated by Kitex v0.7.2. DO NOT EDIT.

package projectservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	project "github.com/li1553770945/sheepim-connect-service/kitex_gen/project"
)

func serviceInfo() *kitex.ServiceInfo {
	return projectServiceServiceInfo
}

var projectServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ProjectService"
	handlerType := (*project.ProjectService)(nil)
	methods := map[string]kitex.MethodInfo{
		"SendMessage": kitex.NewMethodInfo(sendMessageHandler, newProjectServiceSendMessageArgs, newProjectServiceSendMessageResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "project",
		"ServiceFilePath": `idl/message.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.2",
		Extra:           extra,
	}
	return svcInfo
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*project.ProjectServiceSendMessageArgs)
	realResult := result.(*project.ProjectServiceSendMessageResult)
	success, err := handler.(project.ProjectService).SendMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProjectServiceSendMessageArgs() interface{} {
	return project.NewProjectServiceSendMessageArgs()
}

func newProjectServiceSendMessageResult() interface{} {
	return project.NewProjectServiceSendMessageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendMessage(ctx context.Context, req *project.SendMessageReq) (r *project.SendMessageResp, err error) {
	var _args project.ProjectServiceSendMessageArgs
	_args.Req = req
	var _result project.ProjectServiceSendMessageResult
	if err = p.c.Call(ctx, "SendMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
