// Code generated by hertz generator.

package connect

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _connectMw() []app.HandlerFunc {
	// your code...
	//return []app.HandlerFunc{
	//	middleware.GetGlobalGlobalAuthMiddleware(),
	//}
	return nil
}
